name: 📅Update GTFS Static in database 🚈🚌

on:
  push:
      paths:
      - '/appdata/gtfs-static/**.zip'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ⛏️Unzip gtfs-static files⛏️
        run: |
          unzip extract-gtfs-static-zips.sh
      - uses: actions/setup-python@v2
        name: 🐍Setup Python environment and requirments🐍
        run : pip install -r ./data-loading-service/requirements.txt
      - name: Update Database with latest data🛢
        run: python ./data-loading-service/app/gtfs_static_updater
        env:
          DB_URI: ${{secrets.URI}}
          TARGET_DB_SCHEMA: "metro_api"