name: 📅Update GTFS Static in database 🚈🚌

on:
  push:
      paths:
      - './appdata/gtfs-static/future-service/**.zip'
      # branches:
      #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout the repo
      - name: ⛏️Unzip gtfs-static files⛏️
        run: |
          unzip extract-gtfs-static-zips.sh
      - uses: actions/setup-python@v2
        name: 🐍Setup Python environment🐍 
      - name: 🚩Install requirements🚩
        run : pip install -r ./data-loading-service/requirements.txt
      - name: Update Database with latest data🛢
        run: python ./data-loading-service/app/gtfs_static_updater
        env:
          DB_URI: ${{secrets.URI}}
          TARGET_DB_SCHEMA: "metro_api"